i_am_a_profile_name:  dbt_cloud_build_bq
  target: dev  
  outputs:
    
    dev:
      type: bigquery
      method: oauth 
      project: dbt-learn-team
      dataset: dbt_liveabilityment360_26Aug
      threads: 4
      keyfile: 
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: service-account
      project: dbt-learn-team
      dataset: dbt_liveabilityment360_26Aug_Prod
      threads: 4
      keyfile: /secrets/dbt-service-keyfile
      timeout_seconds: 300
      priority: interactive
      retries: 1